export * as SkillCurator from "./curator"

import { Context, Effect, Layer, Schema } from "effect"
import { makeLocationNode } from "../effect/app-node"
import { SkillLearning } from "./learning"

/**
 * SkillCurator — quality control for the self-learning skill pipeline.
 *
 * Skills are auto-generated by SelfLearning from session transcripts, but
 * there's no feedback loop: bad skills accumulate, good skills go unrefined,
 * and dead skills waste context budget. The curator scores learned skills on
 * usage metrics + content quality, prunes the dead weight, and exposes stats
 * so the CLI (and eventually the agent) can make informed curation decisions.
 */

export const SkillScore = Schema.Struct({
  name: Schema.String,
  score: Schema.Number,
  usage: Schema.Struct({
    times_used: Schema.Number,
    times_improved: Schema.Number,
    last_used_ago_ms: Schema.optional(Schema.Number),
  }),
  quality: Schema.Struct({
    has_description: Schema.Boolean,
    has_sections: Schema.Boolean,
    has_gotchas: Schema.Boolean,
    content_length: Schema.Number,
    structure_score: Schema.Number,
  }),
})
export type SkillScore = typeof SkillScore.Type

export const SkillReview = Schema.Struct({
  name: Schema.String,
  verdict: Schema.Literals(["keep", "improve", "prune"]),
  score: Schema.Number,
  reasons: Schema.Array(Schema.String),
})
export type SkillReview = typeof SkillReview.Type

export const CuratorStats = Schema.Struct({
  total: Schema.Number,
  avg_score: Schema.Number,
  keep: Schema.Number,
  improve: Schema.Number,
  prune: Schema.Number,
  scores: Schema.Array(SkillScore),
})
export type CuratorStats = typeof CuratorStats.Type

export interface Interface {
  /** Score a single learned skill (0-100). */
  readonly score: (name: string) => Effect.Effect<SkillScore | undefined>
  /** Score all learned skills and return aggregate stats. */
  readonly stats: () => Effect.Effect<CuratorStats>
  /** Review a skill and return a verdict (keep/improve/prune). */
  readonly review: (name: string) => Effect.Effect<SkillReview | undefined>
  /** Prune skills below a score threshold. Returns removed names. */
  readonly prune: (threshold?: number) => Effect.Effect<string[]>
}

export class Service extends Context.Service<Service, Interface>()("@advcode/skill-curator") {}

// --- Scoring internals ---

const USAGE_MAX = 40
const IMPROVE_MAX = 20
const RECENCY_MAX = 20
const QUALITY_MAX = 20
const SCORE_MAX = USAGE_MAX + IMPROVE_MAX + RECENCY_MAX + QUALITY_MAX

/** Logarithmic usage score: first use is worth a lot, diminishing returns after. */
const usageScore = (timesUsed: number): number => {
  if (timesUsed === 0) return 0
  // log2(1)=0, log2(2)=1, log2(8)=3, log2(32)=5
  const log = Math.log2(timesUsed + 1)
  return Math.min(USAGE_MAX, Math.round((log / 6) * USAGE_MAX))
}

/** Improvement score: each improvement is worth diminishing points. */
const improveScore = (timesImproved: number): number => {
  if (timesImproved === 0) return 0
  const log = Math.log2(timesImproved + 1)
  return Math.min(IMPROVE_MAX, Math.round((log / 4) * IMPROVE_MAX))
}

/** Recency score: used recently = higher score, decays over 30 days. */
const recencyScore = (lastUsedAt: number | null | undefined): number => {
  if (!lastUsedAt) return 0
  const ageMs = Date.now() - lastUsedAt
  const thirtyDays = 30 * 24 * 60 * 60 * 1000
  if (ageMs >= thirtyDays) return 0
  return Math.round(RECENCY_MAX * (1 - ageMs / thirtyDays))
}

/** Content quality heuristic: structure + description + gotchas. */
const qualityScore = (content: string, description: string | undefined): SkillScore["quality"] => {
  const hasDescription = description !== undefined && description.length > 0
  const lowerContent = content.toLowerCase()
  const hasSections = /^##\s+/m.test(content)
  const hasGotchas = lowerContent.includes("gotcha") || lowerContent.includes("pitfall") || lowerContent.includes("warning") || lowerContent.includes("caveat")
  const contentLength = content.length

  let structureScore = 0
  if (hasDescription) structureScore += 5
  if (hasSections) structureScore += 5
  if (hasGotchas) structureScore += 5
  if (contentLength > 100) structureScore += 3
  if (contentLength > 500) structureScore += 2

  return {
    has_description: hasDescription,
    has_sections: hasSections,
    has_gotchas: hasGotchas,
    content_length: contentLength,
    structure_score: Math.min(structureScore, QUALITY_MAX),
  }
}

/** Combine all dimensions into a 0-100 score. */
const computeScore = (
  name: string,
  timesUsed: number,
  timesImproved: number,
  lastUsedAt: number | null | undefined,
  content: string,
  description: string | undefined,
): SkillScore => {
  const usage = usageScore(timesUsed)
  const improve = improveScore(timesImproved)
  const recency = recencyScore(lastUsedAt)
  const quality = qualityScore(content, description)
  const total = usage + improve + recency + quality.structure_score

  return {
    name,
    score: Math.min(SCORE_MAX, total),
    usage: {
      times_used: timesUsed,
      times_improved: timesImproved,
      last_used_ago_ms: lastUsedAt ? Date.now() - lastUsedAt : undefined,
    },
    quality,
  }
}

/** Determine verdict from score. */
const verdict = (score: number): SkillReview["verdict"] => {
  if (score >= 50) return "keep"
  if (score >= 15) return "improve"
  return "prune"
}

const reviewReasons = (scored: SkillScore): string[] => {
  const reasons: string[] = []
  if (scored.usage.times_used === 0) reasons.push("never used")
  if (scored.usage.times_used > 0 && scored.usage.times_used <= 2) reasons.push("barely used")
  if (!scored.quality.has_description) reasons.push("missing description")
  if (!scored.quality.has_sections) reasons.push("no markdown sections")
  if (!scored.quality.has_gotchas) reasons.push("no gotchas/pitfalls section")
  if (scored.quality.content_length < 100) reasons.push("suspiciously short content")
  if (scored.usage.times_improved === 0 && scored.usage.times_used > 5) reasons.push("used often but never improved")
  return reasons
}

// --- Service implementation ---

const layer = Layer.effect(
  Service,
  Effect.gen(function* () {
    const learning = yield* SkillLearning.Service

    const scoreOne = Effect.fn("SkillCurator.scoreOne")(function* (name: string) {
      const skill = yield* learning.get(name)
      if (!skill) return undefined
      return computeScore(
        name,
        skill.times_used,
        skill.times_improved,
        skill.last_used_at ?? null,
        skill.content,
        skill.description,
      )
    })

    const scoreAll = Effect.fn("SkillCurator.scoreAll")(function* () {
      const all = yield* learning.list()
      return yield* Effect.forEach(
        all,
        (skill) =>
          Effect.succeed(
            computeScore(
              skill.name,
              skill.times_used,
              skill.times_improved,
              skill.last_used_at ?? null,
              skill.content,
              skill.description,
            ),
          ),
        { concurrency: 8 },
      )
    })

    return Service.of({
      score: scoreOne,

      stats: Effect.fn("SkillCurator.stats")(function* () {
        const scores = yield* scoreAll()
        const total = scores.length
        if (total === 0) return { total: 0, avg_score: 0, keep: 0, improve: 0, prune: 0, scores: [] }

        let keep = 0
        let improve = 0
        let prune = 0
        for (const s of scores) {
          const v = verdict(s.score)
          if (v === "keep") keep++
          else if (v === "improve") improve++
          else prune++
        }
        const avg = Math.round(scores.reduce((sum, s) => sum + s.score, 0) / total)

        return { total, avg_score: avg, keep, improve, prune, scores }
      }),

      review: Effect.fn("SkillCurator.review")(function* (name: string) {
        const scored = yield* scoreOne(name)
        if (!scored) return undefined
        return {
          name,
          verdict: verdict(scored.score),
          score: scored.score,
          reasons: reviewReasons(scored),
        }
      }),

      prune: Effect.fn("SkillCurator.prune")(function* (threshold = 15) {
        const scores = yield* scoreAll()
        const toRemove = scores.filter((s) => s.score < threshold).map((s) => s.name)
        yield* Effect.forEach(toRemove, (name) => learning.remove(name), { concurrency: 4, discard: true })
        return toRemove
      }),
    })
  }),
)

export const node = makeLocationNode({ service: Service, layer, deps: [SkillLearning.node] })
